Introduction to Pandas
=====================

## Learning Objectives

## Acknowledgements
Some of the examples in this notebook are taken from:
[Python Crash Course - A Hands-on, Project-based, introduction to programming](https://www.amazon.co.uk/Python-Crash-Course-Hands-Project-Based/dp/1593276036), [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)
and https://chrisalbon.com/

Data taken from: [Hadley Wickham's Github Repository and R Data Package](https://github.com/hadley/nycflights13)

In [1]:
# Import Modules
import numpy as np
import pandas as pd

In [2]:
# Create Dataframe
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70]}

In [3]:
# Note: this looks similar to a dictionary as we saw last week.
data

{'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
 'age': [42, 52, 36, 24, 73],
 'preTestScore': [4, 24, 31, 2, 3],
 'postTestScore': [25, 94, 57, 62, 70]}

In [4]:
# Now we name the columns of the dataframe.
df = pd.DataFrame(data, columns = ['name', 'age', 'preTestScore', 'postTestScore'])

In [5]:
# Convention - df stands for dataframe
df

    name  age  preTestScore  postTestScore
0  Jason   42             4             25
1  Molly   52            24             94
2   Tina   36            31             57
3   Jake   24             2             62
4    Amy   73             3             70

In [6]:
# The sum of all the ages
df['age'].sum()

227

In [7]:
# The Average PreTest score
# Note we are pointing to one column and then applying a function to that column.
df['preTestScore'].mean()

12.8

In [8]:
# Note this adds the cumulative score from the first row and heads down   
df['preTestScore'].cumsum()

0     4
1    28
2    59
3    61
4    64
Name: preTestScore, dtype: int64

In [9]:
# All summary statistics for a particular column
df['preTestScore'].describe()

count     5.000000
mean     12.800000
std      13.663821
min       2.000000
25%       3.000000
50%       4.000000
75%      24.000000
max      31.000000
Name: preTestScore, dtype: float64

In [10]:
# Count the number of non NA values
df['preTestScore'].count()

5

In [11]:
# Output the minimum value in this Column
df['preTestScore'].min()

2

In [12]:
# Output the maximum value in this Column
df['preTestScore'].max()

31

In [13]:
# Output the median value in this Column
df['preTestScore'].median()

4.0

In [14]:
# Output the variance in this Column
df['preTestScore'].var()

186.7

In [15]:
# Output the standard deviation of this Column
df['preTestScore'].std()

13.663820841916802

In [16]:
# Output the skewness value of this Column
df['preTestScore'].skew()

0.7433452457326751

In [17]:
# Output the kurtosis value of this Column
df['preTestScore'].kurt()

-2.4673543738411547

In [18]:
# Output the correlation matrix for this dataframe.
df.corr()

                    age  preTestScore  postTestScore
age            1.000000     -0.105651       0.328852
preTestScore  -0.105651      1.000000       0.378039
postTestScore  0.328852      0.378039       1.000000

In [19]:
# Output the covariance matrix for this dataframe.
df.cov()

                  age  preTestScore  postTestScore
age            340.80        -26.65         151.20
preTestScore   -26.65        186.70         128.65
postTestScore  151.20        128.65         620.30

In [20]:
# Load the flights dataset from a CSV and put this into a dataset.
flights = pd.read_csv("flights.csv")

In [21]:
# Output the dimensions of this dataframe (rows and columns).
flights.shape

(336776, 20)

In [22]:
# Output the first few rows of a dataset. This value is 5 by default but you can change this by adding a value in the brackets.
flights.head()
# flights.head(10) # Outputs the first 10 rows of the dataframe.

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00

In [23]:
# Delete column specified
del flights['Unnamed: 0']

In [26]:
# Query the dataframe and match all rows that meet the specified criteria, in this case month = 1 and day = 1.
flights.query("month == 1 & day == 1")

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01 05:00:00
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,2013-01-01 06:00:00
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,2013-01-01 06:00:00
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,2013-01-01 06:00:00
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,2013-01-01 06:00:00
10,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,49,N793JB,JFK,PBI,149.0,1028,6,0,2013-01-01 06:00:00
11,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,71,N657JB,JFK,TPA,158.0,1005,6,0,2013-01-01 06:00:00
12,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,194,N29129,JFK,LAX,345.0,2475,6,0,2013-01-01 06:00:00
13,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,1124,N53441,EWR,SFO,361.0,2565,6,0,2013-01-01 06:00:00
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,2013-01-01 06:00:00
15,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,1806,N708JB,JFK,BOS,44.0,187,5,59,2013-01-01 05:00:00
16,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,1187,N76515,EWR,LAS,337.0,2227,6,0,2013-01-01 06:00:00
17,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,371,N595JB,LGA,FLL,152.0,1076,6,0,2013-01-01 06:00:00
18,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,4650,N542MQ,LGA,ATL,134.0,762,6,0,2013-01-01 06:00:00
19,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,343,N644JB,EWR,PBI,147.0,1023,6,0,2013-01-01 06:00:00
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,2013-01-01 06:00:00
21,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,4401,N730MQ,LGA,DTW,105.0,502,6,5,2013-01-01 06:00:00
22,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,1895,N633AA,EWR,MIA,152.0,1085,6,10,2013-01-01 06:00:00
23,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,1743,N3739P,JFK,ATL,128.0,760,6,10,2013-01-01 06:00:00
24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,2013-01-01 06:00:00
25,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,3768,N9EAMQ,EWR,ORD,139.0,719,6,0,2013-01-01 06:00:00
26,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,303,N532UA,JFK,SFO,366.0,2586,6,0,2013-01-01 06:00:00
27,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,135,N635JB,JFK,RSW,175.0,1074,6,10,2013-01-01 06:00:00
28,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,709,N794JB,JFK,SJU,182.0,1598,6,15,2013-01-01 06:00:00
29,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,575,N326NB,EWR,ATL,120.0,746,6,15,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,2013,1,1,2140.0,2135,5.0,210.0,224,-14.0,B6,701,N284JB,JFK,SJU,189.0,1598,21,35,2013-01-01 21:00:00
813,2013,1,1,2157.0,2155,2.0,43.0,41,2.0,B6,43,N537JB,JFK,MCO,140.0,944,21,55,2013-01-01 21:00:00
814,2013,1,1,2158.0,2200,-2.0,2254.0,2307,-13.0,EV,4103,N14998,EWR,BWI,36.0,169,22,0,2013-01-01 22:00:00
815,2013,1,1,2205.0,1720,285.0,46.0,2040,246.0,AA,1999,N5DNAA,EWR,MIA,146.0,1085,17,20,2013-01-01 17:00:00
816,2013,1,1,2209.0,2145,24.0,58.0,37,21.0,B6,35,N608JB,JFK,PBI,143.0,1028,21,45,2013-01-01 21:00:00
817,2013,1,1,2209.0,2155,14.0,2400.0,2337,23.0,B6,1109,N216JB,JFK,RDU,86.0,427,21,55,2013-01-01 21:00:00
818,2013,1,1,2211.0,2145,26.0,2339.0,2311,28.0,B6,104,N228JB,JFK,BUF,64.0,301,21,45,2013-01-01 21:00:00
819,2013,1,1,2217.0,2229,-12.0,249.0,315,-26.0,B6,713,N547JB,JFK,SJU,191.0,1598,22,29,2013-01-01 22:00:00
820,2013,1,1,2217.0,2130,47.0,140.0,27,73.0,B6,21,N516JB,JFK,TPA,163.0,1005,21,30,2013-01-01 21:00:00
821,2013,1,1,2221.0,2000,141.0,2331.0,2124,127.0,EV,4462,N13566,EWR,BUF,56.0,282,20,0,2013-01-01 20:00:00
822,2013,1,1,2224.0,2200,24.0,2324.0,2316,8.0,EV,4206,N16561,EWR,PWM,47.0,284,22,0,2013-01-01 22:00:00
823,2013,1,1,2229.0,2159,30.0,149.0,100,49.0,B6,11,N531JB,JFK,FLL,153.0,1069,21,59,2013-01-01 21:00:00
824,2013,1,1,2240.0,2245,-5.0,2340.0,2356,-16.0,B6,608,N279JB,JFK,PWM,44.0,273,22,45,2013-01-01 22:00:00
825,2013,1,1,2250.0,2255,-5.0,2352.0,2359,-7.0,B6,1018,N521JB,JFK,BOS,37.0,187,22,55,2013-01-01 22:00:00
826,2013,1,1,2302.0,2200,62.0,2342.0,2253,49.0,EV,4276,N13903,EWR,BDL,24.0,116,22,0,2013-01-01 22:00:00
827,2013,1,1,2306.0,2245,21.0,28.0,5,23.0,B6,30,N281JB,JFK,ROC,59.0,264,22,45,2013-01-01 22:00:00
828,2013,1,1,2307.0,2245,22.0,32.0,2357,35.0,B6,128,N178JB,JFK,BTV,59.0,266,22,45,2013-01-01 22:00:00
829,2013,1,1,2310.0,2255,15.0,24.0,15,9.0,B6,112,N646JB,JFK,BUF,57.0,301,22,55,2013-01-01 22:00:00
830,2013,1,1,2312.0,2000,192.0,21.0,2110,191.0,EV,4312,N13958,EWR,DCA,44.0,199,20,0,2013-01-01 20:00:00
831,2013,1,1,2323.0,2200,83.0,22.0,2313,69.0,EV,4257,N13538,EWR,BTV,44.0,266,22,0,2013-01-01 22:00:00
832,2013,1,1,2326.0,2130,116.0,131.0,18,73.0,B6,199,N594JB,JFK,LAS,290.0,2248,21,30,2013-01-01 21:00:00
833,2013,1,1,2327.0,2250,37.0,32.0,2359,33.0,B6,22,N639JB,JFK,SYR,45.0,209,22,50,2013-01-01 22:00:00
834,2013,1,1,2343.0,1724,379.0,314.0,1938,456.0,EV,4321,N21197,EWR,MCI,222.0,1092,17,24,2013-01-01 17:00:00
835,2013,1,1,2353.0,2359,-6.0,425.0,445,-20.0,B6,739,N591JB,JFK,PSE,195.0,1617,23,59,2013-01-01 23:00:00
836,2013,1,1,2353.0,2359,-6.0,418.0,442,-24.0,B6,707,N794JB,JFK,SJU,185.0,1598,23,59,2013-01-01 23:00:00
837,2013,1,1,2356.0,2359,-3.0,425.0,437,-12.0,B6,727,N588JB,JFK,BQN,186.0,1576,23,59,2013-01-01 23:00:00
838,2013,1,1,NaN,1630,NaN,NaN,1815,NaN,EV,4308,N18120,EWR,RDU,NaN,416,16,30,2013-01-01 16:00:00
839,2013,1,1,NaN,1935,NaN,NaN,2240,NaN,AA,791,N3EHAA,LGA,DFW,NaN,1389,19,35,2013-01-01 19:00:00
840,2013,1,1,NaN,1500,NaN,NaN,1825,NaN,AA,1925,N3EVAA,LGA,MIA,NaN,1096,15,0,2013-01-01 15:00:00
841,2013,1,1,NaN,600,NaN,NaN,901,NaN,B6,125,N618JB,JFK,FLL,NaN,1069,6,0,2013-01-01 06:00:00

In [25]:
# Select rows between the two values. In this case the first row to the 10th row.
flights.iloc[:9]
# flights.iloc[10:19] # This would select the 11th row to the 20th row.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01 05:00:00
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,2013-01-01 06:00:00
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,2013-01-01 06:00:00
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,2013-01-01 06:00:00

In [26]:
# This sorts the dataset in ascending order by the columns given. If multiple columns are given, then it will sort according to the first
# column, then the second column, then the third column.
flights.sort_values(by=['year', 'month', 'day'])

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01 05:00:00
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,2013-01-01 06:00:00
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,2013-01-01 06:00:00
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,2013-01-01 06:00:00
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,2013-01-01 06:00:00
10,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,49,N793JB,JFK,PBI,149.0,1028,6,0,2013-01-01 06:00:00
11,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,71,N657JB,JFK,TPA,158.0,1005,6,0,2013-01-01 06:00:00
12,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,194,N29129,JFK,LAX,345.0,2475,6,0,2013-01-01 06:00:00
13,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,1124,N53441,EWR,SFO,361.0,2565,6,0,2013-01-01 06:00:00
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,2013-01-01 06:00:00
15,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,1806,N708JB,JFK,BOS,44.0,187,5,59,2013-01-01 05:00:00
16,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,1187,N76515,EWR,LAS,337.0,2227,6,0,2013-01-01 06:00:00
17,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,371,N595JB,LGA,FLL,152.0,1076,6,0,2013-01-01 06:00:00
18,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,4650,N542MQ,LGA,ATL,134.0,762,6,0,2013-01-01 06:00:00
19,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,343,N644JB,EWR,PBI,147.0,1023,6,0,2013-01-01 06:00:00
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,2013-01-01 06:00:00
21,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,4401,N730MQ,LGA,DTW,105.0,502,6,5,2013-01-01 06:00:00
22,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,1895,N633AA,EWR,MIA,152.0,1085,6,10,2013-01-01 06:00:00
23,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,1743,N3739P,JFK,ATL,128.0,760,6,10,2013-01-01 06:00:00
24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,2013-01-01 06:00:00
25,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,3768,N9EAMQ,EWR,ORD,139.0,719,6,0,2013-01-01 06:00:00
26,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,303,N532UA,JFK,SFO,366.0,2586,6,0,2013-01-01 06:00:00
27,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,135,N635JB,JFK,RSW,175.0,1074,6,10,2013-01-01 06:00:00
28,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,709,N794JB,JFK,SJU,182.0,1598,6,15,2013-01-01 06:00:00
29,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,575,N326NB,EWR,ATL,120.0,746,6,15,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111266,2013,12,31,2155.0,2039,76.0,253.0,2355,NaN,B6,1205,N627JB,JFK,PDX,NaN,2454,20,39,2013-12-31 20:00:00
111267,2013,12,31,2155.0,2150,5.0,110.0,51,19.0,B6,1901,N729JB,JFK,FLL,164.0,1069,21,50,2013-12-31 21:00:00
111268,2013,12,31,2159.0,2155,4.0,55.0,46,9.0,B6,2053,N593JB,JFK,PBI,155.0,1028,21,55,2013-12-31 21:00:00
111269,2013,12,31,2206.0,2110,56.0,44.0,2339,65.0,B6,775,N184JB,JFK,MSY,195.0,1182,21,10,2013-12-31 21:00:00
111270,2013,12,31,2211.0,2159,12.0,100.0,45,15.0,B6,1183,N715JB,JFK,MCO,148.0,944,21,59,2013-12-31 21:00:00
111271,2013,12,31,2218.0,2219,-1.0,315.0,304,11.0,B6,1203,N625JB,JFK,SJU,202.0,1598,22,19,2013-12-31 22:00:00
111272,2013,12,31,2235.0,2245,-10.0,2351.0,2355,-4.0,B6,234,N355JB,JFK,BTV,49.0,266,22,45,2013-12-31 22:00:00
111273,2013,12,31,2245.0,2250,-5.0,2359.0,2356,3.0,B6,1816,N318JB,JFK,SYR,51.0,209,22,50,2013-12-31 22:00:00
111274,2013,12,31,2310.0,2255,15.0,7.0,2356,11.0,B6,718,N279JB,JFK,BOS,40.0,187,22,55,2013-12-31 22:00:00
111275,2013,12,31,2321.0,2250,31.0,46.0,8,38.0,B6,2002,N179JB,JFK,BUF,66.0,301,22,50,2013-12-31 22:00:00
111276,2013,12,31,2328.0,2330,-2.0,412.0,409,3.0,B6,1389,N651JB,EWR,SJU,198.0,1608,23,30,2013-12-31 23:00:00
111277,2013,12,31,2332.0,2245,47.0,58.0,3,55.0,B6,486,N334JB,JFK,ROC,60.0,264,22,45,2013-12-31 22:00:00
111278,2013,12,31,2355.0,2359,-4.0,430.0,440,-10.0,B6,1503,N509JB,JFK,SJU,195.0,1598,23,59,2013-12-31 23:00:00
111279,2013,12,31,2356.0,2359,-3.0,436.0,445,-9.0,B6,745,N665JB,JFK,PSE,200.0,1617,23,59,2013-12-31 23:00:00
111280,2013,12,31,NaN,1520,NaN,NaN,1705,NaN,AA,341,N568AA,LGA,ORD,NaN,733,15,20,2013-12-31 15:00:00
111281,2013,12,31,NaN,2025,NaN,NaN,2205,NaN,AA,371,N482AA,LGA,ORD,NaN,733,20,25,2013-12-31 20:00:00
111282,2013,12,31,NaN,1932,NaN,NaN,2305,NaN,B6,161,N516JB,JFK,SMF,NaN,2521,19,32,2013-12-31 19:00:00
111283,2013,12,31,NaN,1505,NaN,NaN,1725,NaN,EV,4181,N24103,EWR,MCI,NaN,1092,15,5,2013-12-31 15:00:00
111284,2013,12,31,NaN,1000,NaN,NaN,1252,NaN,UA,1124,NaN,EWR,EGE,NaN,1725,10,0,2013-12-31 10:00:00
111285,2013,12,31,NaN,840,NaN,NaN,1205,NaN,UA,1151,NaN,EWR,SEA,NaN,2402,8,40,2013-12-31 08:00:00
111286,2013,12,31,NaN,754,NaN,NaN,1118,NaN,UA,1455,NaN,EWR,LAX,NaN,2454,7,54,2013-12-31 07:00:00
111287,2013,12,31,NaN,2000,NaN,NaN,2146,NaN,UA,1482,NaN,EWR,ORD,NaN,719,20,0,2013-12-31 20:00:00
111288,2013,12,31,NaN,1500,NaN,NaN,1817,NaN,UA,1483,NaN,EWR,AUS,NaN,1504,15,0,2013-12-31 15:00:00
111289,2013,12,31,NaN,1430,NaN,NaN,1750,NaN,UA,1493,NaN,EWR,LAX,NaN,2454,14,30,2013-12-31 14:00:00
111290,2013,12,31,NaN,855,NaN,NaN,1142,NaN,UA,1506,NaN,EWR,JAC,NaN,1874,8,55,2013-12-31 08:00:00
111291,2013,12,31,NaN,705,NaN,NaN,931,NaN,UA,1729,NaN,EWR,DEN,NaN,1605,7,5,2013-12-31 07:00:00
111292,2013,12,31,NaN,825,NaN,NaN,1029,NaN,US,1831,NaN,JFK,CLT,NaN,541,8,25,2013-12-31 08:00:00
111293,2013,12,31,NaN,1615,NaN,NaN,1800,NaN,MQ,3301,N844MQ,LGA,RDU,NaN,431,16,15,2013-12-31 16:00:00
111294,2013,12,31,NaN,600,NaN,NaN,735,NaN,UA,219,NaN,EWR,ORD,NaN,719,6,0,2013-12-31 06:00:00
111295,2013,12,31,NaN,830,NaN,NaN,1154,NaN,UA,443,NaN,JFK,LAX,NaN,2475,8,30,2013-12-31 08:00:00

In [ ]:
# This sorts the dataset in descending order by the columns given. If multiple columns are given, then it will sort according to the first
# column, then the second column, then the third column.
flights.sort_values(by=['year', 'month', 'day'], ascending=False)

In [27]:
# Returns just the columns specified. Note the double square brackets.
flights[['year', 'month', 'day']]

        year  month  day
0       2013      1    1
1       2013      1    1
2       2013      1    1
3       2013      1    1
4       2013      1    1
5       2013      1    1
6       2013      1    1
7       2013      1    1
8       2013      1    1
9       2013      1    1
10      2013      1    1
11      2013      1    1
12      2013      1    1
13      2013      1    1
14      2013      1    1
15      2013      1    1
16      2013      1    1
17      2013      1    1
18      2013      1    1
19      2013      1    1
20      2013      1    1
21      2013      1    1
22      2013      1    1
23      2013      1    1
24      2013      1    1
25      2013      1    1
26      2013      1    1
27      2013      1    1
28      2013      1    1
29      2013      1    1
...      ...    ...  ...
336746  2013      9   30
336747  2013      9   30
336748  2013      9   30
336749  2013      9   30
336750  2013      9   30
336751  2013      9   30
336752  2013      9   30
336753  2013      9   30
336754  2013      9   30
336755  2013      9   30
336756  2013      9   30
336757  2013      9   30
336758  2013      9   30
336759  2013      9   30
336760  2013      9   30
336761  2013      9   30
336762  2013      9   30
336763  2013      9   30
336764  2013      9   30
336765  2013      9   30
336766  2013      9   30
336767  2013      9   30
336768  2013      9   30
336769  2013      9   30
336770  2013      9   30
336771  2013      9   30
336772  2013      9   30
336773  2013      9   30
336774  2013      9   30
336775  2013      9   30

[336776 rows x 3 columns]

In [28]:
# This line renames the column tail_num, and returns only that column. 
flights.rename(columns={'tailnum': 'tail_num'})['tail_num']

0         N14228
1         N24211
2         N619AA
3         N804JB
4         N668DN
5         N39463
6         N516JB
7         N829AS
8         N593JB
9         N3ALAA
10        N793JB
11        N657JB
12        N29129
13        N53441
14        N3DUAA
15        N708JB
16        N76515
17        N595JB
18        N542MQ
19        N644JB
20        N971DL
21        N730MQ
22        N633AA
23        N3739P
24        N53442
25        N9EAMQ
26        N532UA
27        N635JB
28        N794JB
29        N326NB
           ...
336746    N712EV
336747    N16546
336748    N807JB
336749    N751EV
336750    N807MQ
336751    N335AA
336752    N12957
336753    N633JB
336754    N627JB
336755    N813UA
336756    N10575
336757    N906XJ
336758    N722EV
336759    N532MQ
336760    N12145
336761    N193JB
336762    N578UA
336763    N804JB
336764    N318JB
336765    N354JB
336766    N281JB
336767    N346JB
336768    N565JB
336769    N516JB
336770    N740EV
336771       NaN
336772       NaN
336773    N535MQ
336774    N511MQ
336775    N839MQ
Name: tail_num, Length: 336776, dtype: object

In [30]:
# This line renames the column tail_num but unlike the command above returns the entire dataframe.
flights.rename(columns={'tailnum': 'tail_num'})

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tail_num,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01 05:00:00
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,2013-01-01 06:00:00
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,2013-01-01 06:00:00
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,2013-01-01 06:00:00
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,2013-01-01 06:00:00
10,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,49,N793JB,JFK,PBI,149.0,1028,6,0,2013-01-01 06:00:00
11,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,71,N657JB,JFK,TPA,158.0,1005,6,0,2013-01-01 06:00:00
12,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,194,N29129,JFK,LAX,345.0,2475,6,0,2013-01-01 06:00:00
13,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,1124,N53441,EWR,SFO,361.0,2565,6,0,2013-01-01 06:00:00
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,2013-01-01 06:00:00
15,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,1806,N708JB,JFK,BOS,44.0,187,5,59,2013-01-01 05:00:00
16,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,1187,N76515,EWR,LAS,337.0,2227,6,0,2013-01-01 06:00:00
17,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,371,N595JB,LGA,FLL,152.0,1076,6,0,2013-01-01 06:00:00
18,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,4650,N542MQ,LGA,ATL,134.0,762,6,0,2013-01-01 06:00:00
19,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,343,N644JB,EWR,PBI,147.0,1023,6,0,2013-01-01 06:00:00
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,2013-01-01 06:00:00
21,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,4401,N730MQ,LGA,DTW,105.0,502,6,5,2013-01-01 06:00:00
22,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,1895,N633AA,EWR,MIA,152.0,1085,6,10,2013-01-01 06:00:00
23,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,1743,N3739P,JFK,ATL,128.0,760,6,10,2013-01-01 06:00:00
24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,2013-01-01 06:00:00
25,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,3768,N9EAMQ,EWR,ORD,139.0,719,6,0,2013-01-01 06:00:00
26,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,303,N532UA,JFK,SFO,366.0,2586,6,0,2013-01-01 06:00:00
27,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,135,N635JB,JFK,RSW,175.0,1074,6,10,2013-01-01 06:00:00
28,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,709,N794JB,JFK,SJU,182.0,1598,6,15,2013-01-01 06:00:00
29,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,575,N326NB,EWR,ATL,120.0,746,6,15,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336746,2013,9,30,2123.0,2125,-2.0,2223.0,2247,-24.0,EV,5489,N712EV,LGA,CHO,45.0,305,21,25,2013-09-30 21:00:00
336747,2013,9,30,2127.0,2129,-2.0,2314.0,2323,-9.0,EV,3833,N16546,EWR,CLT,72.0,529,21,29,2013-09-30 21:00:00
336748,2013,9,30,2128.0,2130,-2.0,2328.0,2359,-31.0,B6,97,N807JB,JFK,DEN,213.0,1626,21,30,2013-09-30 21:00:00
336749,2013,9,30,2129.0,2059,30.0,2230.0,2232,-2.0,EV,5048,N751EV,LGA,RIC,45.0,292,20,59,2013-09-30 20:00:00
336750,2013,9,30,2131.0,2140,-9.0,2225.0,2255,-30.0,MQ,3621,N807MQ,JFK,DCA,36.0,213,21,40,2013-09-30 21:00:00
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-09-30 21:00:00
336752,2013,9,30,2142.0,2129,13.0,2250.0,2239,11.0,EV,4509,N12957,EWR,PWM,47.0,284,21,29,2013-09-30 21:00:00
336753,2013,9,30,2145.0,2145,0.0,115.0,140,-25.0,B6,1103,N633JB,JFK,SJU,192.0,1598,21,45,2013-09-30 21:00:00
336754,2013,9,30,2147.0,2137,10.0,30.0,27,3.0,B6,1371,N627JB,LGA,FLL,139.0,1076,21,37,2013-09-30 21:00:00
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-09-30 21:00:00
336756,2013,9,30,2150.0,2159,-9.0,2250.0,2306,-16.0,EV,3842,N10575,EWR,MHT,39.0,209,21,59,2013-09-30 21:00:00
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30 18:00:00
336758,2013,9,30,2203.0,2205,-2.0,2339.0,2331,8.0,EV,5311,N722EV,LGA,BGR,61.0,378,22,5,2013-09-30 22:00:00
336759,2013,9,30,2207.0,2140,27.0,2257.0,2250,7.0,MQ,3660,N532MQ,LGA,BNA,97.0,764,21,40,2013-09-30 21:00:00
336760,2013,9,30,2211.0,2059,72.0,2339.0,2242,57.0,EV,4672,N12145,EWR,STL,120.0,872,20,59,2013-09-30 20:00:00
336761,2013,9,30,2231.0,2245,-14.0,2335.0,2356,-21.0,B6,108,N193JB,JFK,PWM,48.0,273,22,45,2013-09-30 22:00:00
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-09-30 21:00:00
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-09-30 20:00:00
336764,2013,9,30,2237.0,2245,-8.0,2345.0,2353,-8.0,B6,234,N318JB,JFK,BTV,43.0,266,22,45,2013-09-30 22:00:00
336765,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,B6,1816,N354JB,JFK,SYR,41.0,209,22,45,2013-09-30 22:00:00
336766,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,B6,2002,N281JB,JFK,BUF,52.0,301,22,50,2013-09-30 22:00:00
336767,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,B6,486,N346JB,JFK,ROC,47.0,264,22,46,2013-09-30 22:00:00
336768,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,B6,718,N565JB,JFK,BOS,33.0,187,22,55,2013-09-30 22:00:00
336769,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,B6,745,N516JB,JFK,PSE,196.0,1617,23,59,2013-09-30 23:00:00
336770,2013,9,30,NaN,1842,NaN,NaN,2019,NaN,EV,5274,N740EV,LGA,BNA,NaN,764,18,42,2013-09-30 18:00:00
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00

In [31]:
# Returns the unique values of tailnum only
flights.tailnum.unique()

array(['N14228', 'N24211', 'N619AA', ..., 'N776SK', 'N785SK', 'N557AS'],
      dtype=object)

In [32]:
# Returns the columns listed and drops any duplicate entries. Looks like there were only 224 routes run.
flights[['origin', 'dest']].drop_duplicates()

       origin dest
0         EWR  IAH
1         LGA  IAH
2         JFK  MIA
3         JFK  BQN
4         LGA  ATL
5         EWR  ORD
6         EWR  FLL
7         LGA  IAD
8         JFK  MCO
9         LGA  ORD
10        JFK  PBI
11        JFK  TPA
12        JFK  LAX
13        EWR  SFO
14        LGA  DFW
15        JFK  BOS
16        EWR  LAS
17        LGA  FLL
19        EWR  PBI
20        LGA  MSP
21        LGA  DTW
22        EWR  MIA
23        JFK  ATL
26        JFK  SFO
27        JFK  RSW
28        JFK  SJU
29        EWR  ATL
30        EWR  PHX
31        LGA  MIA
33        EWR  MSP
...       ...  ...
27377     JFK  ACK
27469     LGA  BGR
27477     LGA  MSN
27606     LGA  ORF
27696     JFK  IAH
27734     JFK  MCI
27738     LGA  OMA
27824     LGA  DSM
27857     LGA  GSP
27881     JFK  ABQ
27927     LGA  ILM
27955     LGA  SYR
29446     JFK  MVY
43734     LGA  SBN
57315     JFK  STL
77948     LGA  LEX
83558     EWR  SBN
100150    LGA  MHT
100631    LGA  CAE
101912    JFK  JAC
102295    JFK  SDF
137120    LGA  CHO
137696    JFK  MKE
177582    LGA  AVL
216127    JFK  BHM
235071    LGA  TVC
235826    LGA  MYR
254470    EWR  TVC
255455    EWR  ANC
275945    EWR  LGA

[224 rows x 2 columns]

In [34]:
# Adds new columns that are calculations of original columns.
flights['gain'] = flights.arr_delay - flights.dep_delay
flights['gain_per_hour'] = flights.gain / (flights.air_time / 60)
flights['speed'] = flights.distance / flights.air_time * 60

In [35]:
flights

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,origin,dest,air_time,distance,hour,minute,time_hour,gain,gain_per_hour,speed
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,9.0,2.378855,370.044053
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,16.0,4.229075,374.273128
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,31.0,11.625000,408.375000
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,-17.0,-5.573770,516.721311
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,-19.0,-9.827586,394.137931
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,...,EWR,ORD,150.0,719,5,58,2013-01-01 05:00:00,16.0,6.400000,287.600000
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,...,EWR,FLL,158.0,1065,6,0,2013-01-01 06:00:00,24.0,9.113924,404.430380
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,...,LGA,IAD,53.0,229,6,0,2013-01-01 06:00:00,-11.0,-12.452830,259.245283
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,...,JFK,MCO,140.0,944,6,0,2013-01-01 06:00:00,-5.0,-2.142857,404.571429
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,...,LGA,ORD,138.0,733,6,0,2013-01-01 06:00:00,10.0,4.347826,318.695652
10,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,...,JFK,PBI,149.0,1028,6,0,2013-01-01 06:00:00,0.0,0.000000,413.959732
11,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,...,JFK,TPA,158.0,1005,6,0,2013-01-01 06:00:00,-1.0,-0.379747,381.645570
12,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,...,JFK,LAX,345.0,2475,6,0,2013-01-01 06:00:00,9.0,1.565217,430.434783
13,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,...,EWR,SFO,361.0,2565,6,0,2013-01-01 06:00:00,-12.0,-1.994460,426.315789
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,...,LGA,DFW,257.0,1389,6,0,2013-01-01 06:00:00,32.0,7.470817,324.280156
15,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,...,JFK,BOS,44.0,187,5,59,2013-01-01 05:00:00,-4.0,-5.454545,255.000000
16,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,...,EWR,LAS,337.0,2227,6,0,2013-01-01 06:00:00,-7.0,-1.246291,396.498516
17,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,...,LGA,FLL,152.0,1076,6,0,2013-01-01 06:00:00,-7.0,-2.763158,424.736842
18,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,...,LGA,ATL,134.0,762,6,0,2013-01-01 06:00:00,12.0,5.373134,341.194030
19,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,...,EWR,PBI,147.0,1023,6,0,2013-01-01 06:00:00,-7.0,-2.857143,417.551020
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,...,LGA,MSP,170.0,1020,6,10,2013-01-01 06:00:00,0.0,0.000000,360.000000
21,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,...,LGA,DTW,105.0,502,6,5,2013-01-01 06:00:00,19.0,10.857143,286.857143
22,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,...,EWR,MIA,152.0,1085,6,10,2013-01-01 06:00:00,-8.0,-3.157895,428.289474
23,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,...,JFK,ATL,128.0,760,6,10,2013-01-01 06:00:00,-4.0,-1.875000,356.250000
24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,...,EWR,MIA,157.0,1085,6,7,2013-01-01 06:00:00,-17.0,-6.496815,414.649682
25,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,...,EWR,ORD,139.0,719,6,0,2013-01-01 06:00:00,24.0,10.359712,310.359712
26,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,...,JFK,SFO,366.0,2586,6,0,2013-01-01 06:00:00,3.0,0.491803,423.934426
27,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,...,JFK,RSW,175.0,1074,6,10,2013-01-01 06:00:00,1.0,0.342857,368.228571
28,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,...,JFK,SJU,182.0,1598,6,15,2013-01-01 06:00:00,-21.0,-6.923077,526.813187
29,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,...,EWR,ATL,120.0,746,6,15,2013-01-01 06:00:00,-9.0,-4.500000,373.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336746,2013,9,30,2123.0,2125,-2.0,2223.0,2247,-24.0,EV,...,LGA,CHO,45.0,305,21,25,2013-09-30 21:00:00,-22.0,-29.333333,406.666667
336747,2013,9,30,2127.0,2129,-2.0,2314.0,2323,-9.0,EV,...,EWR,CLT,72.0,529,21,29,2013-09-30 21:00:00,-7.0,-5.833333,440.833333
336748,2013,9,30,2128.0,2130,-2.0,2328.0,2359,-31.0,B6,...,JFK,DEN,213.0,1626,21,30,2013-09-30 21:00:00,-29.0,-8.169014,458.028169
336749,2013,9,30,2129.0,2059,30.0,2230.0,2232,-2.0,EV,...,LGA,RIC,45.0,292,20,59,2013-09-30 20:00:00,-32.0,-42.666667,389.333333
336750,2013,9,30,2131.0,2140,-9.0,2225.0,2255,-30.0,MQ,...,JFK,DCA,36.0,213,21,40,2013-09-30 21:00:00,-21.0,-35.000000,355.000000
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,...,JFK,LAX,298.0,2475,21,40,2013-09-30 21:00:00,-30.0,-6.040268,498.322148
336752,2013,9,30,2142.0,2129,13.0,2250.0,2239,11.0,EV,...,EWR,PWM,47.0,284,21,29,2013-09-30 21:00:00,-2.0,-2.553191,362.553191
336753,2013,9,30,2145.0,2145,0.0,115.0,140,-25.0,B6,...,JFK,SJU,192.0,1598,21,45,2013-09-30 21:00:00,-25.0,-7.812500,499.375000
336754,2013,9,30,2147.0,2137,10.0,30.0,27,3.0,B6,...,LGA,FLL,139.0,1076,21,37,2013-09-30 21:00:00,-7.0,-3.021583,464.460432
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,...,EWR,BOS,37.0,200,21,56,2013-09-30 21:00:00,-16.0,-25.945946,324.324324
336756,2013,9,30,2150.0,2159,-9.0,2250.0,2306,-16.0,EV,...,EWR,MHT,39.0,209,21,59,2013-09-30 21:00:00,-7.0,-10.769231,321.538462
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,...,JFK,BUF,50.0,301,18,45,2013-09-30 18:00:00,0.0,0.000000,361.200000
336758,2013,9,30,2203.0,2205,-2.0,2339.0,2331,8.0,EV,...,LGA,BGR,61.0,378,22,5,2013-09-30 22:00:00,10.0,9.836066,371.803279
336759,2013,9,30,2207.0,2140,27.0,2257.0,2250,7.0,MQ,...,LGA,BNA,97.0,764,21,40,2013-09-30 21:00:00,-20.0,-12.371134,472.577320
336760,2013,9,30,2211.0,2059,72.0,2339.0,2242,57.0,EV,...,EWR,STL,120.0,872,20,59,2013-09-30 20:00:00,-15.0,-7.500000,436.000000
336761,2013,9,30,2231.0,2245,-14.0,2335.0,2356,-21.0,B6,...,JFK,PWM,48.0,273,22,45,2013-09-30 22:00:00,-7.0,-8.750000,341.250000
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,...,EWR,SFO,318.0,2565,21,13,2013-09-30 21:00:00,-38.0,-7.169811,483.962264
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,...,JFK,MCO,123.0,944,20,1,2013-09-30 20:00:00,-24.0,-11.707317,460.487805
336764,2013,9,30,2237.0,2245,-8.0,2345.0,2353,-8.0,B6,...,JFK,BTV,43.0,266,22,45,2013-09-30 22:00:00,0.0,0.000000,371.162791
336765,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,B6,...,JFK,SYR,41.0,209,22,45,2013-09-30 22:00:00,-12.0,-17.560976,305.853659
336766,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,B6,...,JFK,BUF,52.0,301,22,50,2013-09-30 22:00:00,-10.0,-11.538462,347.307692
336767,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,B6,...,JFK,ROC,47.0,264,22,46,2013-09-30 22:00:00,-11.0,-14.042553,337.021277
336768,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,B6,...,JFK,BOS,33.0,187,22,55,2013-09-30 22:00:00,-11.0,-20.000000,340.000000
336769,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,B6,...,JFK,PSE,196.0,1617,23,59,2013-09-30 23:00:00,-15.0,-4.591837,495.000000
336770,2013,9,30,NaN,1842,NaN,NaN,2019,NaN,EV,...,LGA,BNA,NaN,764,18,42,2013-09-30 18:00:00,NaN,NaN,NaN
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,...,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,NaN,NaN,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,...,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,NaN,NaN,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,...,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,NaN,NaN,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,...,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,NaN,NaN,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,...,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,NaN,NaN,NaN

In [36]:
flights[['gain', 'gain_per_hour']]

        gain  gain_per_hour
0        9.0       2.378855
1       16.0       4.229075
2       31.0      11.625000
3      -17.0      -5.573770
4      -19.0      -9.827586
5       16.0       6.400000
6       24.0       9.113924
7      -11.0     -12.452830
8       -5.0      -2.142857
9       10.0       4.347826
10       0.0       0.000000
11      -1.0      -0.379747
12       9.0       1.565217
13     -12.0      -1.994460
14      32.0       7.470817
15      -4.0      -5.454545
16      -7.0      -1.246291
17      -7.0      -2.763158
18      12.0       5.373134
19      -7.0      -2.857143
20       0.0       0.000000
21      19.0      10.857143
22      -8.0      -3.157895
23      -4.0      -1.875000
24     -17.0      -6.496815
25      24.0      10.359712
26       3.0       0.491803
27       1.0       0.342857
28     -21.0      -6.923077
29      -9.0      -4.500000
...      ...            ...
336746 -22.0     -29.333333
336747  -7.0      -5.833333
336748 -29.0      -8.169014
336749 -32.0     -42.666667
336750 -21.0     -35.000000
336751 -30.0      -6.040268
336752  -2.0      -2.553191
336753 -25.0      -7.812500
336754  -7.0      -3.021583
336755 -16.0     -25.945946
336756  -7.0     -10.769231
336757   0.0       0.000000
336758  10.0       9.836066
336759 -20.0     -12.371134
336760 -15.0      -7.500000
336761  -7.0      -8.750000
336762 -38.0      -7.169811
336763 -24.0     -11.707317
336764   0.0       0.000000
336765 -12.0     -17.560976
336766 -10.0     -11.538462
336767 -11.0     -14.042553
336768 -11.0     -20.000000
336769 -15.0      -4.591837
336770   NaN            NaN
336771   NaN            NaN
336772   NaN            NaN
336773   NaN            NaN
336774   NaN            NaN
336775   NaN            NaN

[336776 rows x 2 columns]

In [40]:
# look at the mean for the specified column.
flights.dep_delay.mean()

12.639070257304708

In [39]:
# This is different to the way specified previously but returns the same result.
flights['dep_delay'].mean()

12.639070257304708

In [42]:
# Return x random records, in this case x = 10. 
flights.loc[np.random.choice(flights.index, 10)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,origin,dest,air_time,distance,hour,minute,time_hour,gain,gain_per_hour,speed
228523,2013,6,7,1925.0,1930,-5.0,2055.0,2117,-22.0,DL,...,LGA,PIT,58.0,335,19,30,2013-06-07 19:00:00,-17.0,-17.586207,346.551724
6084,2013,1,7,2205.0,2107,58.0,4.0,2322,42.0,EV,...,EWR,SDF,103.0,642,21,7,2013-01-07 21:00:00,-16.0,-9.320388,373.980583
250797,2013,7,1,1209.0,1130,39.0,1507.0,1415,52.0,UA,...,EWR,MCO,145.0,937,11,30,2013-07-01 11:00:00,13.0,5.379310,387.724138
195559,2013,5,3,840.0,841,-1.0,1041.0,1039,2.0,EV,...,EWR,AVL,87.0,583,8,41,2013-05-03 08:00:00,3.0,2.068966,402.068966
167171,2013,4,3,744.0,745,-1.0,1006.0,1011,-5.0,DL,...,EWR,ATL,115.0,746,7,45,2013-04-03 07:00:00,-4.0,-2.086957,389.217391
225340,2013,6,4,1408.0,1415,-7.0,1507.0,1525,-18.0,EV,...,EWR,MHT,38.0,209,14,15,2013-06-04 14:00:00,-11.0,-17.368421,330.000000
213872,2013,5,22,2342.0,2045,177.0,151.0,2313,158.0,B6,...,JFK,MSY,171.0,1182,20,45,2013-05-22 20:00:00,-19.0,-6.666667,414.736842
90672,2013,12,9,709.0,638,31.0,1023.0,931,52.0,UA,...,EWR,MCO,144.0,937,6,38,2013-12-09 06:00:00,21.0,8.750000,390.416667
108859,2013,12,29,906.0,849,17.0,1118.0,1106,12.0,EV,...,EWR,CHS,104.0,628,8,49,2013-12-29 08:00:00,-5.0,-2.884615,362.307692
27063,2013,10,1,629.0,635,-6.0,825.0,833,-8.0,EV,...,EWR,MSP,154.0,1008,6,35,2013-10-01 06:00:00,-2.0,-0.779221,392.727273

In [44]:
flights.iloc[np.random.randint(0, len(flights), .1  * len(flights))]

TypeError: 'float' object cannot be interpreted as an integer

In [46]:
planes_df = flights.groupby('tailnum')
delay = planes_df.agg({"year": "count",
                       "distance": "mean", 
                       "arr_delay": "mean"})
delay.query("year > 20 & distance < 2000")

         year    distance  arr_delay
tailnum
N0EGMQ    371  676.188679   9.982955
N10156    153  757.947712  12.717241
N102UW     48  535.875000   2.937500
N103US     46  535.195652  -6.934783
N104UW     47  535.255319   1.804348
N10575    289  519.702422  20.691450
N105UW     45  524.844444  -0.266667
N107US     41  528.707317  -5.731707
N108UW     60  534.500000  -1.250000
N109UW     48  535.875000  -2.520833
N110UW     40  535.375000   2.800000
N11106    129  771.410853  14.880952
N11107    148  705.864865  15.014388
N11109    148  714.000000  14.851064
N11113    138  719.775362  15.761905
N11119    148  723.385135  30.306569
N11121    154  719.370130  10.306122
N11127    124  748.112903  13.605042
N11137    112  726.598214  20.551402
N11140    157  747.210191  18.312057
N11150    136  775.558824   8.891473
N11155     98  779.122449  12.989583
N11164    143  677.447552  21.649635
N11165    159  752.880503   8.346667
N11176    142  729.070423  20.404580
N11181    125  705.416000   9.075000
N11184    136  744.051471   6.984375
N11187    133  733.887218  11.190476
N11189    140  684.271429   6.737226
N11191    136  734.375000  21.935484
...       ...         ...        ...
N984DL     58  904.741379   4.228070
N985AT     29  647.896552  15.038462
N985DL     63  905.111111   0.253968
N986AT     24  654.541667   0.125000
N986DL     73  943.780822   5.583333
N987AT     28  618.607143  37.384615
N987DL     55  922.872727  -3.290909
N988AT     37  642.972973  44.342857
N988DL     55  864.200000   9.471698
N989AT     66  694.818182  28.193548
N989DL     89  908.685393  11.034091
N990AT     71  731.605634  16.385714
N990DL     56  863.035714  12.428571
N991AT     25  659.800000  15.680000
N991DL     92  902.923913   7.336957
N992AT     38  637.131579  17.783784
N992DL     57  902.754386  -6.649123
N993AT     47  606.680851  10.404255
N993DL     55  884.909091  16.981132
N994AT     31  698.483871  31.483871
N994DL     61  886.786885   5.032787
N995DL     57  883.578947   1.929825
N996AT     29  673.896552   6.538462
N996DL    102  897.303922   0.524752
N997AT     44  679.045455  16.302326
N997DL     63  867.761905   4.903226
N998AT     26  593.538462  29.960000
N998DL     77  857.818182  16.394737
N999DN     61  895.459016  14.311475
N9EAMQ    248  674.665323   9.235294

[2961 rows x 3 columns]

In [48]:
destinations = flights.groupby("dest")
destinations.agg({
    'tailnum': lambda x: len(x.unique()),
    'year': 'count'
}).rename(columns={'tailnum': 'planes',
                  'year': 'flights'})

      planes  flights
dest
ABQ      108      254
ACK       58      265
ALB      172      439
ANC        6        8
ATL     1180    17215
AUS      993     2439
AVL      159      275
BDL      186      443
BGR       46      375
BHM       45      297
BNA      963     6333
BOS     1308    15508
BQN      268      896
BTV      390     2589
BUF      504     4681
BUR      120      371
BWI      632     1781
BZN       32       36
CAE       89      116
CAK       90      864
CHO       25       52
CHS      450     2884
CLE      961     4573
CLT      822    14064
CMH      465     3524
CRW       20      138
CVG      564     3941
DAY      333     1525
DCA      470     9705
DEN     1251     7266
...      ...      ...
PIT      703     2875
PSE      122      365
PSP        9       19
PVD      162      376
PWM      366     2352
RDU      606     8163
RIC      415     2454
ROC      508     2416
RSW      720     3537
SAN      762     2737
SAT      311      686
SAV      226      804
SBN       10       10
SDF      303     1157
SEA      936     3923
SFO      855    13331
SJC      118      329
SJU      728     5819
SLC      378     2467
SMF      110      284
SNA      214      825
SRQ      373     1211
STL      960     4339
STT       87      522
SYR      383     1761
TPA     1126     7466
TUL      105      315
TVC       60      101
TYS      273      631
XNA      176     1036

[105 rows x 2 columns]

In [49]:
daily = flights.groupby(['year', 'month', 'day'])
per_day = daily['distance'].count()
per_day

year  month  day
2013  1      1       842
             2       943
             3       914
             4       915
             5       720
             6       832
             7       933
             8       899
             9       902
             10      932
             11      930
             12      690
             13      828
             14      928
             15      894
             16      901
             17      927
             18      924
             19      674
             20      786
             21      912
             22      890
             23      897
             24      925
             25      922
             26      680
             27      823
             28      923
             29      890
             30      900
                    ...
      12     2      1004
             3       973
             4       958
             5       969
             6       970
             7       691
             8       875
             9       962
             10      943
             11      954
             12      968
             13      970
             14      692
             15      880
             16      964
             17      949
             18      956
             19      974
             20      980
             21      811
             22      895
             23      985
             24      761
             25      719
             26      936
             27      963
             28      814
             29      888
             30      968
             31      776
Name: distance, Length: 365, dtype: int64

In [50]:
per_month = per_day.groupby(level=['year', 'month']).sum()
per_month

year  month
2013  1        27004
      2        24951
      3        28834
      4        28330
      5        28796
      6        28243
      7        29425
      8        29327
      9        27574
      10       28889
      11       27268
      12       28135
Name: distance, dtype: int64

In [51]:
per_year = per_month.sum()
per_year

336776

In [52]:
(
flights.groupby(['year', 'month', 'day'])
    [['arr_delay', 'dep_delay']]
    .mean()
    .query('arr_delay > 30 | dep_delay > 30')
)

                arr_delay  dep_delay
year month day
2013 1     16   34.247362  24.612865
           31   32.602854  28.658363
     2     11   36.290094  39.073598
           27   31.252492  37.763274
     3     8    85.862155  83.536921
           18   41.291892  30.117960
     4     10   38.412311  33.023675
           12   36.048140  34.838428
           18   36.028481  34.915361
           19   47.911697  46.127828
           22   37.812166  30.642553
           25   33.681250  23.339564
     5     8    39.609183  43.217778
           23   61.970899  51.144720
           24   24.257415  30.340717
     6     2    26.075518  34.013366
           10   28.022293  30.619450
           13   63.753689  45.790828
           18   37.648026  35.950766
           24   51.176808  47.157418
           25   41.513684  43.063025
           26   27.317410  30.611752
           27   44.783296  40.891232
           28   44.976852  48.827784
           30   43.510278  44.188179
     7     1    58.280502  56.233825
           7    40.306378  36.617450
           8    29.648847  37.296646
           9    31.334365  30.711499
           10   59.626478  52.860702
           22   62.763403  46.667047
           23   44.959821  44.741685
           28   49.831776  37.710162
     8     1    35.989259  34.574034
           8    55.481163  43.349947
           9    43.313641  34.691898
           22   29.976744  33.600421
           28   35.203074  40.526894
     9     2    45.518430  53.029551
           12   58.912418  49.958750
     10    7    39.017260  39.146710
           11   18.922995  31.231838
     12    5    51.666255  52.327990
           8    36.911801  21.515337
           9    42.575556  34.800221
           10   44.508796  26.465494
           14   46.397504  28.361552
           17   55.871856  40.705602
           23   32.226042  32.254149

Missing values

In [53]:
flights.isnull()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,origin,dest,air_time,distance,hour,minute,time_hour,gain,gain_per_hour,speed
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336746,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336747,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336748,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336749,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336750,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336751,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336752,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336753,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336754,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336755,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336756,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336757,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336758,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336759,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336760,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336761,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336762,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336763,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336764,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336765,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336766,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336767,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336768,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336769,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336770,False,False,False,True,False,True,True,False,True,False,...,False,False,True,False,False,False,False,True,True,True
336771,False,False,False,True,False,True,True,False,True,False,...,False,False,True,False,False,False,False,True,True,True
336772,False,False,False,True,False,True,True,False,True,False,...,False,False,True,False,False,False,False,True,True,True
336773,False,False,False,True,False,True,True,False,True,False,...,False,False,True,False,False,False,False,True,True,True
336774,False,False,False,True,False,True,True,False,True,False,...,False,False,True,False,False,False,False,True,True,True
336775,False,False,False,True,False,True,True,False,True,False,...,False,False,True,False,False,False,False,True,True,True

In [54]:
flights.dropna()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,origin,dest,air_time,distance,hour,minute,time_hour,gain,gain_per_hour,speed
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,9.0,2.378855,370.044053
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,16.0,4.229075,374.273128
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,31.0,11.625000,408.375000
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,-17.0,-5.573770,516.721311
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,-19.0,-9.827586,394.137931
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,...,EWR,ORD,150.0,719,5,58,2013-01-01 05:00:00,16.0,6.400000,287.600000
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,...,EWR,FLL,158.0,1065,6,0,2013-01-01 06:00:00,24.0,9.113924,404.430380
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,...,LGA,IAD,53.0,229,6,0,2013-01-01 06:00:00,-11.0,-12.452830,259.245283
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,...,JFK,MCO,140.0,944,6,0,2013-01-01 06:00:00,-5.0,-2.142857,404.571429
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,...,LGA,ORD,138.0,733,6,0,2013-01-01 06:00:00,10.0,4.347826,318.695652
10,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,...,JFK,PBI,149.0,1028,6,0,2013-01-01 06:00:00,0.0,0.000000,413.959732
11,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,...,JFK,TPA,158.0,1005,6,0,2013-01-01 06:00:00,-1.0,-0.379747,381.645570
12,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,...,JFK,LAX,345.0,2475,6,0,2013-01-01 06:00:00,9.0,1.565217,430.434783
13,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,...,EWR,SFO,361.0,2565,6,0,2013-01-01 06:00:00,-12.0,-1.994460,426.315789
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,...,LGA,DFW,257.0,1389,6,0,2013-01-01 06:00:00,32.0,7.470817,324.280156
15,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,...,JFK,BOS,44.0,187,5,59,2013-01-01 05:00:00,-4.0,-5.454545,255.000000
16,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,...,EWR,LAS,337.0,2227,6,0,2013-01-01 06:00:00,-7.0,-1.246291,396.498516
17,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,...,LGA,FLL,152.0,1076,6,0,2013-01-01 06:00:00,-7.0,-2.763158,424.736842
18,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,...,LGA,ATL,134.0,762,6,0,2013-01-01 06:00:00,12.0,5.373134,341.194030
19,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,...,EWR,PBI,147.0,1023,6,0,2013-01-01 06:00:00,-7.0,-2.857143,417.551020
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,...,LGA,MSP,170.0,1020,6,10,2013-01-01 06:00:00,0.0,0.000000,360.000000
21,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,...,LGA,DTW,105.0,502,6,5,2013-01-01 06:00:00,19.0,10.857143,286.857143
22,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,...,EWR,MIA,152.0,1085,6,10,2013-01-01 06:00:00,-8.0,-3.157895,428.289474
23,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,...,JFK,ATL,128.0,760,6,10,2013-01-01 06:00:00,-4.0,-1.875000,356.250000
24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,...,EWR,MIA,157.0,1085,6,7,2013-01-01 06:00:00,-17.0,-6.496815,414.649682
25,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,...,EWR,ORD,139.0,719,6,0,2013-01-01 06:00:00,24.0,10.359712,310.359712
26,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,...,JFK,SFO,366.0,2586,6,0,2013-01-01 06:00:00,3.0,0.491803,423.934426
27,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,...,JFK,RSW,175.0,1074,6,10,2013-01-01 06:00:00,1.0,0.342857,368.228571
28,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,...,JFK,SJU,182.0,1598,6,15,2013-01-01 06:00:00,-21.0,-6.923077,526.813187
29,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,...,EWR,ATL,120.0,746,6,15,2013-01-01 06:00:00,-9.0,-4.500000,373.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336740,2013,9,30,2115.0,2110,5.0,2246.0,2255,-9.0,MQ,...,LGA,DTW,72.0,502,21,10,2013-09-30 21:00:00,-14.0,-11.666667,418.333333
336741,2013,9,30,2116.0,2124,-8.0,2317.0,2337,-20.0,EV,...,EWR,SDF,94.0,642,21,24,2013-09-30 21:00:00,-12.0,-7.659574,409.787234
336742,2013,9,30,2119.0,2005,74.0,2310.0,2212,58.0,EV,...,EWR,MCI,147.0,1092,20,5,2013-09-30 20:00:00,-16.0,-6.530612,445.714286
336743,2013,9,30,2119.0,2120,-1.0,2330.0,2354,-24.0,B6,...,JFK,JAX,113.0,828,21,20,2013-09-30 21:00:00,-23.0,-12.212389,439.646018
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,...,JFK,LAX,296.0,2475,21,0,2013-09-30 21:00:00,-46.0,-9.324324,501.689189
336745,2013,9,30,2122.0,2127,-5.0,2226.0,2237,-11.0,EV,...,EWR,DCA,35.0,199,21,27,2013-09-30 21:00:00,-6.0,-10.285714,341.142857
336746,2013,9,30,2123.0,2125,-2.0,2223.0,2247,-24.0,EV,...,LGA,CHO,45.0,305,21,25,2013-09-30 21:00:00,-22.0,-29.333333,406.666667
336747,2013,9,30,2127.0,2129,-2.0,2314.0,2323,-9.0,EV,...,EWR,CLT,72.0,529,21,29,2013-09-30 21:00:00,-7.0,-5.833333,440.833333
336748,2013,9,30,2128.0,2130,-2.0,2328.0,2359,-31.0,B6,...,JFK,DEN,213.0,1626,21,30,2013-09-30 21:00:00,-29.0,-8.169014,458.028169
336749,2013,9,30,2129.0,2059,30.0,2230.0,2232,-2.0,EV,...,LGA,RIC,45.0,292,20,59,2013-09-30 20:00:00,-32.0,-42.666667,389.333333
336750,2013,9,30,2131.0,2140,-9.0,2225.0,2255,-30.0,MQ,...,JFK,DCA,36.0,213,21,40,2013-09-30 21:00:00,-21.0,-35.000000,355.000000
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,...,JFK,LAX,298.0,2475,21,40,2013-09-30 21:00:00,-30.0,-6.040268,498.322148
336752,2013,9,30,2142.0,2129,13.0,2250.0,2239,11.0,EV,...,EWR,PWM,47.0,284,21,29,2013-09-30 21:00:00,-2.0,-2.553191,362.553191
336753,2013,9,30,2145.0,2145,0.0,115.0,140,-25.0,B6,...,JFK,SJU,192.0,1598,21,45,2013-09-30 21:00:00,-25.0,-7.812500,499.375000
336754,2013,9,30,2147.0,2137,10.0,30.0,27,3.0,B6,...,LGA,FLL,139.0,1076,21,37,2013-09-30 21:00:00,-7.0,-3.021583,464.460432
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,...,EWR,BOS,37.0,200,21,56,2013-09-30 21:00:00,-16.0,-25.945946,324.324324
336756,2013,9,30,2150.0,2159,-9.0,2250.0,2306,-16.0,EV,...,EWR,MHT,39.0,209,21,59,2013-09-30 21:00:00,-7.0,-10.769231,321.538462
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,...,JFK,BUF,50.0,301,18,45,2013-09-30 18:00:00,0.0,0.000000,361.200000
336758,2013,9,30,2203.0,2205,-2.0,2339.0,2331,8.0,EV,...,LGA,BGR,61.0,378,22,5,2013-09-30 22:00:00,10.0,9.836066,371.803279
336759,2013,9,30,2207.0,2140,27.0,2257.0,2250,7.0,MQ,...,LGA,BNA,97.0,764,21,40,2013-09-30 21:00:00,-20.0,-12.371134,472.577320
336760,2013,9,30,2211.0,2059,72.0,2339.0,2242,57.0,EV,...,EWR,STL,120.0,872,20,59,2013-09-30 20:00:00,-15.0,-7.500000,436.000000
336761,2013,9,30,2231.0,2245,-14.0,2335.0,2356,-21.0,B6,...,JFK,PWM,48.0,273,22,45,2013-09-30 22:00:00,-7.0,-8.750000,341.250000
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,...,EWR,SFO,318.0,2565,21,13,2013-09-30 21:00:00,-38.0,-7.169811,483.962264
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,...,JFK,MCO,123.0,944,20,1,2013-09-30 20:00:00,-24.0,-11.707317,460.487805
336764,2013,9,30,2237.0,2245,-8.0,2345.0,2353,-8.0,B6,...,JFK,BTV,43.0,266,22,45,2013-09-30 22:00:00,0.0,0.000000,371.162791
336765,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,B6,...,JFK,SYR,41.0,209,22,45,2013-09-30 22:00:00,-12.0,-17.560976,305.853659
336766,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,B6,...,JFK,BUF,52.0,301,22,50,2013-09-30 22:00:00,-10.0,-11.538462,347.307692
336767,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,B6,...,JFK,ROC,47.0,264,22,46,2013-09-30 22:00:00,-11.0,-14.042553,337.021277
336768,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,B6,...,JFK,BOS,33.0,187,22,55,2013-09-30 22:00:00,-11.0,-20.000000,340.000000
336769,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,B6,...,JFK,PSE,196.0,1617,23,59,2013-09-30 23:00:00,-15.0,-4.591837,495.000000

In [55]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [56]:
data.isna()

a    False
b     True
c    False
d     True
e    False
dtype: bool

In [57]:
data.dropna()

a    1.0
c    2.0
e    3.0
dtype: float64

In [58]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [59]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [60]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
# forward-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

Joins

In [61]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display(df1, df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [62]:
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [63]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

In [64]:
display(df3, df4, pd.merge(df3, df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [65]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
display(df1, df5, pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [66]:
display(df1, df2, pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014